# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
defaults: &defaults
  working_directory: /tmp
  docker:
    - image: circleci/node:7.10

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: workspace
          # Must be relative path from root
          paths:
            - echo-output
  audit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run: yarn flow
      - run: yarn lint
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run: yarn test:cov
      - run: yarn report-coverage
  test-prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run: yarn test:prod
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - audit:
          requires:
            - build
      - test:
          requires:
            - build
      - test-prod:
          requires:
            - build
